version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/microservces_vsqlite/pedidos
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      # Step 3: pytest
      - run:
          name: run test
          command: |
            . venv/bin/activate
            python test_pedidos.py
      # Step 4: behave test
      # - run:
      #     name: behave test
      #     command: |
      #       . venv/bin/activate
      #       behave